const interiors = [
    "", 
    "47th Annual Kips Bay Decorator Show in New York City, with Young Huh Studio.",
    "",
    "",
    "",
    "", 
    "Private apartment in Philadelphia",
    "", 
    "", 
    "", 
    "", 
    "", 
    "Private apartment in Rome, Italy.",
    "", 
    "", 
    "", 
    "Resort in Turks & Caicos Islands.",
    "", 
    "", 
    "", 
    "", 
    "", 
    "Private apartment in New York City.",
    "", 
    "", 
    "", 
    "Gut renovation of coworking space in the heart of Roma, Italy.", 
    "", 
    "", 
    "", 
    "", 
    "Private apartment in Rome, Italy.", 

];

const furniture = [
    "", 
    "Den of Thieves at Salone del Mobile Milano, Italy. ", 
    "", 
    "", 
    "Chopping boards collection.", 
    "Tables details.", 
    "", 
    "Commisioned table for shared space of the WeWork office in Toronto.",
    "",
    "",
    "Huge twin, bar height, rolling tables for Loyal Kaspar's New York City office.",
    "", 
    "Den of Thieves chopping boards collection."
];

const patterns = [
    "", 
    "Custom Wallpaper for private residence.", 
    "Custom Bisazza mosaic for a resort in Turks & Caicos.", 
    "", 
    "", 
    "Custom rug for private residence.", 
    "", 
    "Floor tiles for private residence.", 
    "", 
    "Custom rug.", 
    "Custom wallpaper for private residence.", 
    "", 
    "Custom tiles.", 
    "", 
    "", 
    "Custom wallpaper for private residence.",
    "", 
    "", 
    "Den of Thieves chopping board colection.",

];